FROM node:20-alpine

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install development dependencies with legacy-peer-deps flag to handle dependency conflicts
RUN npm install --legacy-peer-deps

# Copy the rest of the application
COPY . .

# Set environment variables
ENV NODE_ENV development
ENV PORT 3000
ENV WATCHPACK_POLLING true

# Expose port 3000
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "start"]